iperf taskfile

diff --git a/.taskfiles/Kubernetes/Taskfile.yaml b/.taskfiles/Kubernetes/Taskfile.yaml
--- a/.taskfiles/Kubernetes/Taskfile.yaml
+++ b/.taskfiles/Kubernetes/Taskfile.yaml
@@ -73,3 +73,67 @@ tasks:
         vars:
           NAME: "{{.CLIENT_NAME}}"
           NS: "{{.CLIENT_NS}}"
+
+  wait-pod-pending:
+    aliases: [waitp]
+    internal: true
+    desc: Wait for a job's pod to change its status to pending
+    vars:
+      NAME: &name-fail '{{ or .NAME (fail "Missing `NAME` environment variable!") }}'
+      NS: &ns-fail '{{ or .NS (fail "Missing `NS` environment variable!") }}'
+    cmds:
+      - |
+        until [[ $(kubectl -n {{.NS}} get pod {{.NAME}} -o jsonpath='{.items[*].status.phase}') == "Pending" ]]; do sleep 1; done
+
+  wait-pod-running:
+    aliases: [waitr]
+    internal: true
+    desc: "Wait for a job's pod to change its status to running"
+    vars:
+      NAME: *name-fail
+      NS: *ns-fail
+    cmds:
+      - until [[ $(kubectl -n {{.NS}} get pod {{.NAME}} -o jsonpath='{.items[*].status.phase}') == "Running" ]]; do sleep 1; done
+
+  wait-pod-running-v2:
+    internal: true
+    desc: Wait for a job's pod to change its status to running
+    vars:
+      NAME: *name-fail
+      NS: *ns-fail
+    cmds:
+      - |
+        until kubectl wait pod -n {{.NS}} {{.NAME}} --for-jsonpath='{.items[*].status.phase}'=Running --timeout=-; do sleep 1; done
+
+  wait-pod-ready:
+    internal: true
+    desc: Wait for a pod to be ready
+    vars:
+      NAME: *name-fail
+      NS: *ns-fail
+    cmds:
+      - until kubectl wait pod -n {{.NS}} {{.NAME}} --for=condition=Ready --timeout=1h; do sleep 1; done
+
+  wait-pod-delete:
+    aliases: [waitd]
+    internal: true
+    desc: Wait for a job's pod to delete
+    vars:
+      NAME: *name-fail
+      NS: *ns-fail
+    cmds:
+      - until kubectl wait pod -n {{.NS}} {{.NAME}} --for delete --timeout=1m; do sleep 1; done
+
+  wait-finish:
+    internal: true
+    desc: Wait for a job's pod to change its status to pending
+    vars:
+      NAME: *name-fail
+      NS: *ns-fail
+      TYPE: '{{ .TYPE | default "job" }}'
+      # WAIT_ARGS: '{{.WAIT_ARGS | default "echo \"{{.NAME}} is still running, logs:\" && kubectl -n {{.NS}} logs {{.NAME}} --since 2s -f;"}}'
+    cmds:
+      - |-
+        until kubectl -n {{.NS}} wait {{.TYPE}}/{{.NAME}} --for condition=complete --timeout=2s; do
+          echo "{{.NAME}} is still running, logs:" && kubectl -n {{.NS}} logs {{.TYPE}}/{{.NAME}} --since 2s -f || true;
+        done
